#!/bin/bash

VERSION=v1.0.5

help() {
  echo "Usage:"
  echo "  zmicro package install gzfetch <args...>"
  echo ""
}

install() {
  # prepare vars
  local name="gzfetch"
  # get system os/arch
  local arch="$(os::arch)"
  local kernel="$(os::kernel)"
  local platform="$(os::platform)"
  # usr_bin_dir
  local usr_bin_dir=$(os::usr_bin_dir)
  local tmp_dir="/tmp/$name"
  # files
  local tmp_file="$name.tar.gz"
  local bin_file="./$name"

  # prepare context
  mkdir -p $tmp_dir
  cd $tmp_dir

  # reference: https://github.com/go-zoox/gzfetch/releases
  # example:
  #   https://github.com/go-zoox/gzfetch/releases/download/v1.0.4/gzfetch_1.0.4_darwin_amd64.tar.gz
  #   https://github.com/go-zoox/gzfetch/releases/download/v1.0.4/gzfetch_1.0.4_darwin_arm64.tar.gz
  # generate url
  local url="https://github.com/go-zoox/gzfetch/releases/download/$VERSION/${name}_${VERSION#v}_${platform}_${arch}.tar.gz"
  log::debug "[package][$name][$kernel][$arch] url: $url"

  # download
  os::curl --progress-bar -fSL $url -o $tmp_file

  # extract
  tar -zxvf $tmp_file >>/dev/null 2>&1

  # install
  sudo mv $bin_file $usr_bin_dir/$name

  # clean
  rm -rf $tmp_dir
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  install
  if [ $? -eq 0 ]; then
    log::success "install gzfetch success."
    exit 0
  else
    log::error "install gzfetch failed."
    exit 1
  fi
}

run() {
  core "$@"
}

if [ "$1" = "ONE_LINE" ]; then
  command -v zmicro # >>/dev/null 2>&1
  if [ $? -ne 0 ]; then
    curl -o- https://raw.githubusercontent.com/zcorky/zmicro/master/install | sh
  fi

  zmicro package install gzfetch
else
  set -e

  run "$@"
fi
